### ISSUE TITLE
MVP List 

### ISSUE THREAD

**Issue by AdamYLiang** [JMBourgoin/Everwrote#1]
- [x] Have a rich text editor as an MVP 
- [x] Notes and notebooks should be two separate MVPs
- [x] Users should be able to remove tags 

If you have any questions or want me to go into detail let me know!

**Comment by JMBourgoin** [comment]
Not sure about my associations, especially with the tags.

**Comment by AdamYLiang** [comment]
I'll check the schema and if there are any issues I'll bring them up and we can discuss them when needed. 
Good changes on the MVP List! I just have a couple of more and it should be good to go: 

- [ ] Separate rich text editor and notes into 2 MVPs since they both will take some time.
- [ ] Include the sidebar into either notebooks or notes since the "New Note" button will live in the sidebar
- [ ] Total of 7 numbered MVPs with optional bonus MVPs if time permitted.
