### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by AdamYLiang** [JMBourgoin/Everwrote#3]
**Notes**
- [x] Change two notes have the different keys (right now they are both `1`)

**Tags** 
- [x] Should have the `id` be a key pointing to each tag

Everything else looks good, let me know if you have any questions or want to talk about the state!

**Comment by JMBourgoin** [comment]
I think I took care of both of those ... the have tag issue:  I saw that I had a repeat of a tag id... is that what you meant?

**Comment by AdamYLiang** [comment]
Yes it is, nice changes!
